name: Publish dockerized package when release occurs

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Build image
        run: |
          image_name=$(cut -d / -f 2 <<< ${{ github.repository }})
          tag_name=${{ github.ref_name }}
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
          docker build . -t ${image_name}:${tag_name}
          docker tag ${image_name}:${tag_name} ${image_name}:latest
          docker push --all-tags ${image_name}